language: objective-c
osx_image: xcode9.1
xcode_project: GoSwiftyM3U8.xcodeproj # path to your xcodeproj folder

env:
  global:
  - IOS_SCHEME="GoSwiftyM3U8-iOSTests"
  - IOS_SDK=iphonesimulator11.1
  - TVOS_SCHEME=GoSwiftyM3U8-tvOSTests
  - TVOS_SDK=appletvsimulator11.1
  - MACOS_SCHEME=GoSwiftyM3U8-macOSTests
  - MACOS_SDK=macosx10.13
  matrix:
    - DESTINATION="OS=11.1,name=iPhone 7" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_SCHEME" SDK="$MACOS_SDK" RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=11.1,name=Apple TV 4K" SCHEME="$TVOS_SCHEME" SDK="$TVOS_SDK" RUN_TESTS="YES" POD_LINT="NO"

script:
  - set -o pipefail
  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    else
      xcodebuild -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --verbose;
    fi

notifications:
  email:
    recipients:
      - gal.orlanczyk@outlook.com
    on_success: change
    on_failure: always
