language: objective-c
xcode_project: GoSwiftyM3U8.xcodeproj # path to your xcodeproj folder

matrix:
  include:
    - xcode_scheme: GoSwiftyM3U8-iOSTests
      xcode_sdk: iphonesimulator11.1
    - xcode_scheme: GoSwiftyM3U8-tvOSTests
      xcode_sdk: tvos9.0
    - xcode_scheme: GoSwiftyM3U8-macOSTests
      xcode_sdk: macosx10.11

before_install:
  - gem install jazzy
  - chmod +x ./scripts/jazzy_update.sh

script:
  - ./scripts/jazzy_update.sh # apple docs generation script

notifications:
  email:
    recipients:
      - gal.orlanczyk@outlook.com
    on_success: change
    on_failure: always